export const translations = {
  en: {
    nav: { talk: "Talk to me →", labs: "Labs", media: "Media", newsletter: "Newsletter", about: "About", home: "Home", soon: "Soon" },
    home: { l1: "Knowledge.", l2: "Tools.", l3: "Community.", body: "A non-profit knowledge hub for industrial cutting professionals and enthusiasts. Plasma, waterjet, laser — explored openly, shared freely.", cta1: "Explore Labs →", cta2: "Our Mission", hsl: "Labs", hst: "Apps & Calculators", hml: "Media", hmt: "Podcast & Video", hnl: "Newsletter · LinkedIn", hnt: "Industrial Cutting", htl: "Direct", htt: "Talk to me", soon: "Soon", st: "Tools in Labs", sy: "Years in cutting", sc: "Technologies covered", sv: "Open access" },
    labs: { label: "Section 01", title: "Labs", desc: "Experimental tools for industrial cutting professionals and hobbyists. No sign-ups required. Your feedback shapes every next build.", disclaimer: "All tools here are experimental. No data is stored or recorded. Information is sourced from publicly available manufacturer data — process tables, cut charts, and published specifications. The author works at Hypertherm but this platform is fully independent and not affiliated with or endorsed by any manufacturer. Use results as reference only.", live: "Live", building: "Building database", buildingSub: "Database in progress", planned: "Planned", igniteName: "Ignite", igniteDesc: "Plasma cutting savings calculator for shipbuilding and heavy fabrication. Final version — multilingual, metric & imperial, PDF export.", igniteCta: "Launch calculator →", cutwiseName: "Cutwise", cutwiseDesc: "Technology comparison calculator — plasma, waterjet, and laser side by side. Built on publicly available manufacturer process data.", cutbotName: "CutBot", cutbotDesc: "AI assistant trained on cutting process knowledge. Ask about amperage, gases, speeds, or consumables — and get a direct, process-aware answer. No generic answers.", processFindName: "Process Finder", processFindDesc: "Input your material and thickness. Get the recommended cutting process — plasma, laser, or waterjet — with the reasoning behind it.", partFindName: "Part Finder", partFindDesc: "Describe what you need — amperage, system, material — and find the part number you can never seem to remember.", feedbackTitle: "Feedback is essential here.", feedbackSub: "These tools are built in the open and improved continuously. Bug reports, suggestions, and real-world results are all welcome — and genuinely used.", feedbackCta: "Send feedback →" },
    media: { label: "Section 02", title: "Media", coming: "Coming Soon", desc: "Deep dives on plasma, waterjet, and laser cutting. Conversations with engineers, fabricators, and the people building the future of industrial cutting.", notifyLabel: "Notify me when it launches", notifyBtn: "Notify me", placeholder: "your@email.com" },
    newsletter: { label: "Newsletter · LinkedIn", title: "Industrial Cutting", desc: "Technical insights, process comparisons, and industry perspectives — delivered to your LinkedIn feed. No fluff, no vendor spin.", cta: "Read on LinkedIn", recent: "Recent posts" },
    about: { label: "Our Mission", title: "Why This Exists", mission: "Industrial Cutting Labs is a personal project born from 12+ years working with plasma, waterjet, and laser cutting across the Americas. It exists to make industrial cutting knowledge openly accessible — to professionals, hobbyists, and anyone curious about the craft. The author works at Hypertherm, but this platform has no manufacturer bias — all content is independent and process-based.", v1t: "Open Access", v1d: "Every tool, article, and resource here is free to access. No subscriptions, no paywalls — and that's not a promotion, it's just how this works.", v2t: "No Manufacturer Bias", v2d: "The author works at Hypertherm, but this platform is fully independent. No sponsored content, no vendor promotion — just honest, process-based knowledge from real-world experience.", v3t: "Thought Leadership", v3d: "Honest, technical conversations about industrial cutting — plasma, waterjet, laser — grounded in real-world experience across the Americas.", v4t: "Community First", v4d: "For professionals, engineers, hobbyists, and students alike. The goal is to grow the community's collective knowledge of cutting processes.", author: "Built by Gui Rossi · Business Development & Cutting Technology Specialist" },
    talk: { label: "Direct contact", title: "Let's talk cutting.", desc: "Whether you're evaluating technology, want to discuss a project, or just have a question about the tools — reach out directly.", nameLbl: "Your name", emailLbl: "Email", msgLbl: "Message", namePh: "Name", emailPh: "email@company.com", msgPh: "What's on your mind?", send: "Send message →" },
    footer: { copy: "© 2026 Industrial Cutting Labs · Gui Rossi", tag: "Open knowledge for the cutting industry." },
  },
  pt: {
    nav: { talk: "Fale comigo →", labs: "Labs", media: "Mídia", newsletter: "Newsletter", about: "Sobre", home: "Início", soon: "Em breve" },
    home: { l1: "Conhecimento.", l2: "Ferramentas.", l3: "Comunidade.", body: "Um hub de conhecimento sem fins lucrativos para profissionais e entusiastas do corte industrial. Plasma, jato d'água, laser — explorados abertamente, compartilhados livremente.", cta1: "Explorar Labs →", cta2: "Nossa Missão", hsl: "Labs", hst: "Apps & Calculadoras", hml: "Mídia", hmt: "Podcast & Vídeo", hnl: "Newsletter · LinkedIn", hnt: "Industrial Cutting", htl: "Direto", htt: "Fale comigo", soon: "Em breve", st: "Ferramentas no Labs", sy: "Anos na indústria", sc: "Tecnologias cobertas", sv: "Acesso aberto" },
    labs: { label: "Seção 01", title: "Labs", desc: "Ferramentas experimentais para profissionais e hobbistas do corte industrial. Sem cadastro obrigatório. Seu feedback molda cada nova versão.", disclaimer: "Todas as ferramentas aqui são experimentais. Nenhum dado é armazenado ou registrado. As informações são obtidas de dados públicos dos fabricantes — tabelas de processos, cut charts e especificações publicadas. O autor trabalha na Hypertherm, mas esta plataforma é totalmente independente, não afiliada nem endossada por nenhum fabricante. Use os resultados apenas como referência.", live: "Disponível", building: "Construindo base de dados", buildingSub: "Base de dados em andamento", planned: "Planejado", igniteName: "Ignite", igniteDesc: "Calculadora de economia em corte plasma para construção naval e fabricação pesada. Versão final — multilíngue, métrico e imperial, exportação PDF.", igniteCta: "Abrir calculadora →", cutwiseName: "Cutwise", cutwiseDesc: "Calculadora de comparação de tecnologias — plasma, jato d'água e laser lado a lado. Baseada em dados públicos de fabricantes.", cutbotName: "CutBot", cutbotDesc: "Assistente de IA treinado em conhecimento de processos de corte. Pergunte sobre amperagem, gases, velocidades ou consumíveis — e receba uma resposta direta e orientada ao processo.", processFindName: "Process Finder", processFindDesc: "Informe seu material e espessura. Receba o processo de corte recomendado — plasma, laser ou jato d'água — com o raciocínio por trás da indicação.", partFindName: "Part Finder", partFindDesc: "Descreva o que você precisa — amperagem, sistema, material — e encontre o número de peça que você nunca consegue lembrar.", feedbackTitle: "Feedback é essencial aqui.", feedbackSub: "Estas ferramentas são construídas de forma aberta e melhoradas continuamente. Relatórios de bugs, sugestões e resultados reais são bem-vindos — e genuinamente usados.", feedbackCta: "Enviar feedback →" },
    media: { label: "Seção 02", title: "Mídia", coming: "Em Breve", desc: "Mergulhos profundos em plasma, jato d'água e laser. Conversas com engenheiros, fabricadores e as pessoas que constroem o futuro do corte industrial.", notifyLabel: "Me avise quando lançar", notifyBtn: "Me avisar", placeholder: "seu@email.com" },
    newsletter: { label: "Newsletter · LinkedIn", title: "Industrial Cutting", desc: "Insights técnicos, comparações de processos e perspectivas do setor — entregues no seu LinkedIn. Sem enrolação, sem viés de fornecedor.", cta: "Ler no LinkedIn", recent: "Posts recentes" },
    about: { label: "Nossa Missão", title: "Por que isso existe", mission: "O Industrial Cutting Labs é um projeto pessoal nascido de mais de 12 anos trabalhando com plasma, jato d'água e laser nas Américas. Existe para tornar o conhecimento sobre corte industrial abertamente acessível — para profissionais, hobbistas e qualquer pessoa curiosa. O autor trabalha na Hypertherm, mas esta plataforma não tem viés de fabricante — todo o conteúdo é independente.", v1t: "Acesso Aberto", v1d: "Cada ferramenta, artigo e recurso aqui é de acesso livre. Sem assinaturas, sem paywalls — não é uma promoção, é simplesmente como funciona.", v2t: "Sem Viés de Fabricante", v2d: "O autor trabalha na Hypertherm, mas esta plataforma é totalmente independente. Sem conteúdo patrocinado, sem promoção de fornecedor — apenas conhecimento honesto baseado em processos reais.", v3t: "Thought Leadership", v3d: "Conversas técnicas honestas sobre corte industrial — plasma, jato d'água, laser — baseadas em experiência real nas Américas.", v4t: "Comunidade em Primeiro", v4d: "Para profissionais, engenheiros, hobbistas e estudantes. O objetivo é expandir o conhecimento coletivo da comunidade sobre processos de corte.", author: "Construído por Gui Rossi · Especialista em Desenvolvimento de Negócios e Tecnologia de Corte" },
    talk: { label: "Contato direto", title: "Vamos falar de corte.", desc: "Seja para avaliar tecnologia, discutir um projeto ou tirar uma dúvida sobre as ferramentas — entre em contato diretamente.", nameLbl: "Seu nome", emailLbl: "E-mail", msgLbl: "Mensagem", namePh: "Nome", emailPh: "email@empresa.com", msgPh: "O que você tem em mente?", send: "Enviar mensagem →" },
    footer: { copy: "© 2026 Industrial Cutting Labs · Gui Rossi", tag: "Conhecimento aberto para a indústria de corte." },
  },
  es: {
    nav: { talk: "Contáctame →", labs: "Labs", media: "Medios", newsletter: "Newsletter", about: "Acerca de", home: "Inicio", soon: "Próximamente" },
    home: { l1: "Conocimiento.", l2: "Herramientas.", l3: "Comunidad.", body: "Un hub de conocimiento sin fines de lucro para profesionales y entusiastas del corte industrial. Plasma, waterjet, láser — explorados abiertamente, compartidos libremente.", cta1: "Explorar Labs →", cta2: "Nuestra Misión", hsl: "Labs", hst: "Apps y Calculadoras", hml: "Medios", hmt: "Podcast y Video", hnl: "Newsletter · LinkedIn", hnt: "Industrial Cutting", htl: "Directo", htt: "Contáctame", soon: "Próximamente", st: "Herramientas en Labs", sy: "Años en la industria", sc: "Tecnologías cubiertas", sv: "Acceso abierto" },
    labs: { label: "Sección 01", title: "Labs", desc: "Herramientas experimentales para profesionales y aficionados del corte industrial. Sin registros requeridos. Tu feedback da forma a cada nueva versión.", disclaimer: "Todas las herramientas aquí son experimentales. No se almacenan ni registran datos. La información proviene de datos públicos de fabricantes — tablas de procesos, cut charts y especificaciones publicadas. El autor trabaja en Hypertherm, pero esta plataforma es totalmente independiente, no afiliada ni respaldada por ningún fabricante. Use los resultados solo como referencia.", live: "Disponible", building: "Construyendo base de datos", buildingSub: "Base de datos en progreso", planned: "Planificado", igniteName: "Ignite", igniteDesc: "Calculadora de ahorro en corte plasma para construcción naval y fabricación pesada. Versión final — multilingüe, métrico e imperial, exportación PDF.", igniteCta: "Abrir calculadora →", cutwiseName: "Cutwise", cutwiseDesc: "Calculadora de comparación de tecnologías — plasma, waterjet y láser lado a lado. Basada en datos públicos de fabricantes.", cutbotName: "CutBot", cutbotDesc: "Asistente de IA entrenado en conocimiento de procesos de corte. Pregúntale sobre amperaje, gases, velocidades o consumibles — y obtén una respuesta directa orientada al proceso.", processFindName: "Process Finder", processFindDesc: "Ingresa tu material y espesor. Obtén el proceso de corte recomendado — plasma, láser o waterjet — con el razonamiento detrás de la recomendación.", partFindName: "Part Finder", partFindDesc: "Describe lo que necesitas — amperaje, sistema, material — y encuentra el número de parte que nunca recuerdas.", feedbackTitle: "El feedback es esencial aquí.", feedbackSub: "Estas herramientas se construyen abiertamente y se mejoran continuamente. Reportes de bugs, sugerencias y resultados reales son bienvenidos — y genuinamente utilizados.", feedbackCta: "Enviar feedback →" },
    media: { label: "Sección 02", title: "Medios", coming: "Próximamente", desc: "Inmersiones profundas en plasma, waterjet y láser. Conversaciones con ingenieros, fabricantes y las personas que construyen el futuro del corte industrial.", notifyLabel: "Avísame cuando lance", notifyBtn: "Avísame", placeholder: "tu@email.com" },
    newsletter: { label: "Newsletter · LinkedIn", title: "Industrial Cutting", desc: "Perspectivas técnicas, comparaciones de procesos y opiniones del sector — entregadas en tu LinkedIn. Sin relleno, sin sesgo de proveedor.", cta: "Leer en LinkedIn", recent: "Posts recientes" },
    about: { label: "Nuestra Misión", title: "Por qué esto existe", mission: "Industrial Cutting Labs es un proyecto personal nacido de más de 12 años trabajando con plasma, waterjet y láser en las Américas. Existe para hacer el conocimiento sobre corte industrial abiertamente accesible — para profesionales, aficionados y cualquier persona curiosa. El autor trabaja en Hypertherm, pero esta plataforma no tiene sesgo de fabricante — todo el contenido es independiente.", v1t: "Acceso Abierto", v1d: "Cada herramienta, artículo y recurso aquí es de acceso libre. Sin suscripciones, sin paywalls — no es una promoción, así es simplemente como funciona.", v2t: "Sin Sesgo de Fabricante", v2d: "El autor trabaja en Hypertherm, pero esta plataforma es totalmente independiente. Sin contenido patrocinado, sin promoción de proveedor — solo conocimiento honesto basado en procesos reales.", v3t: "Thought Leadership", v3d: "Conversaciones técnicas honestas sobre corte industrial — plasma, waterjet, láser — basadas en experiencia real en las Américas.", v4t: "Comunidad Primero", v4d: "Para profesionales, ingenieros, aficionados y estudiantes. El objetivo es expandir el conocimiento colectivo de la comunidad sobre procesos de corte.", author: "Construido por Gui Rossi · Especialista en Desarrollo de Negocios y Tecnología de Corte" },
    talk: { label: "Contacto directo", title: "Hablemos de corte.", desc: "Ya sea para evaluar tecnología, discutir un proyecto o hacer una pregunta — contáctame directamente.", nameLbl: "Tu nombre", emailLbl: "Correo", msgLbl: "Mensaje", namePh: "Nombre", emailPh: "correo@empresa.com", msgPh: "¿Qué tienes en mente?", send: "Enviar mensaje →" },
    footer: { copy: "© 2026 Industrial Cutting Labs · Gui Rossi", tag: "Conocimiento abierto para la industria del corte." },
  },
};

export function detectLang() {
  const bl = (navigator.language || navigator.userLanguage || 'en').toLowerCase();
  if (bl.startsWith('pt')) return 'pt';
  if (bl.startsWith('es')) return 'es';
  return 'en';
}
